sudo: false
language: ruby
rvm:
- 2.3.3
- 2.4.0
cache: bundler
script:
- xvfb-run bundle exec rake test
- bundle exec bundle-audit check --update
notifications:
  email:
    on_success: never
    on_failure: always
