language: ruby
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      rvm: 2.4.5
    - os: linux
      dist: trusty
      sudo: false
      rvm: 2.5.2
    - os: linux
      dist: trusty
      sudo: false
      rvm: 2.6.0
    - os: linux
      dist: trusty
      sudo: false
      rvm: ruby-head
    - os: osx
      osx_image: xcode8.2
      rvm: 2.4.5
    - os: osx
      osx_image: xcode8.2
      rvm: 2.5.2
    - os: osx
      osx_image: xcode8.2
      rvm: 2.6.0
    - os: osx
      osx_image: xcode8.2
      rvm: ruby-head
  allow_failures:
    - os: osx
    - rvm: ruby-head
  fast_finish: true
cache: bundler
before_install:
  - gem update --system
  - gem install bundler-audit
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        xvfb-run bundle exec rake test;
    else
        bundle exec rake test;
    fi
  - bundle-audit check --update
env:
  global:
    UPLOAD_TO_CODECOV: 1
notifications:
  email:
    on_success: never
    on_failure: always
addons:
  apt:
    packages:
      - xclip
