name: auto-merge bump_version_to_v*

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: ${{ github.repository == 'shugo/textbringer' && startsWith(github.head_ref, 'bump_version_to_v') }}
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve
      - name: Enable auto-merge for bump_version_to_v* PRs
        run: gh pr merge --merge --auto "$PR_URL"
