name: macos

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: bundle exec rake test
