name: Publish gem to rubygems.org

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  push:
    if: ${{ github.repository == 'shugo/textbringer' && startsWith(github.head_ref, 'bump_version_to_v') }}
    runs-on: ubuntu-latest

    environment:
      name: rubygems.org
      url: https://rubygems.org/gems/textbringer
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      pull-requests: write
      contents: write
      id-token: write

    steps:
      # Merge PR
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve

      - name: Enable auto-merge for bump_version_to_v* PRs
        run: gh pr merge --merge --auto "$PR_URL"

      # Set up
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1

      - name: Create GitHub release
        run: |
          version="$(ruby -r ./lib/textbringer/version -e 'print Textbringer::VERSION')"
          tag_name="v${version}"
          gh release create "${tag_name}" --verify-tag --draft --generate-notes
