name: ubuntu

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: [ head, 3.1, 3.0, 2.7 ]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        sudo apt install libncursesw5-dev
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: xvfb-run bundle exec rake test
