name: ubuntu

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: [ '2.7', '2.6', '2.5', '2.4' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        sudo apt install libncursesw5-dev
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: xvfb-run bundle exec rake test
      env:
       UPLOAD_TO_CODECOV: 1
       CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
