name: ubuntu

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ head, 3.4, 3.3, 3.2 ]
    timeout-minutes: 10
    env:
      RUBYOPT: --enable-frozen-string-literal --debug-frozen-string-literal
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        sudo apt install libncursesw5-dev
        bundle install
    - name: Run test
      run: xvfb-run bundle exec rake test
