name: windows

on: [push]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 'mingw', 'mswin', '3.3' ]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run test
      run: bundle exec rake test
