name: windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 'mingw', 'mswin', '2.7', '2.6', '2.5' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run test
      run: bundle exec rake test
